#!/usr/bin/env bash
# Generate /etc/nginx/conf.d/cloudflare-realip.conf from Cloudflare's published
# ranges, so nginx restores the visitor's real IP from CF-Connecting-IP.
#
# This is HALF of a pair. The other half is TRUST_PROXY=1 in backend.env.
# Neither works alone:
#   * nginx only    -> the backend ignores the header, still sees 127.0.0.1
#   * TRUST_PROXY only -> the backend trusts an address nginx never wrote,
#                         so it buckets by Cloudflare edge IP instead of visitor
# With neither, the rate limiter and the per-(user, ip) login lockout collapse
# into ONE shared counter and a single attacker can lock out every account.
#
# Run as root on the origin host, then verify a real IP appears in
# /var/log/nginx/access.log before setting TRUST_PROXY=1:
#
#   sudo ./cloudflare-realip.sh
#
# Re-run whenever Cloudflare changes its ranges (rare). Delete the generated
# file if you ever move off Cloudflare — with no trusted source in front,
# CF-Connecting-IP is just a header anyone can set.
set -euo pipefail

OUT="${OUT:-/etc/nginx/conf.d/cloudflare-realip.conf}"
TMP="$(mktemp)"; V4="$(mktemp)"; V6="$(mktemp)"
trap 'rm -f "$TMP" "$V4" "$V6"' EXIT

curl -fsS https://www.cloudflare.com/ips-v4 -o "$V4"
curl -fsS https://www.cloudflare.com/ips-v6 -o "$V6"

# Cloudflare's lists have NO trailing newline, so a plain `cat v4 v6` glues the
# last IPv4 range onto the first IPv6 range and silently produces one corrupt
# CIDR. `awk 1` re-terminates every record.
{
    echo "# Generated by infra/deploy/cloudflare-realip.sh on $(date -u +%FT%TZ)"
    echo "# Do not edit by hand — re-run the script instead."
    echo "# Pairs with TRUST_PROXY=1 in backend.env; see DEPLOYMENT.md."
    awk 1 "$V4" "$V6" | grep . | sed 's|^|set_real_ip_from |; s|$|;|'
    echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

n="$(grep -c '^set_real_ip_from' "$TMP" || true)"
if [[ "$n" -lt 15 ]]; then
    echo "only $n ranges fetched — refusing to install a partial list" >&2
    exit 1
fi

cp "$TMP" "$OUT"
nginx -t
systemctl reload nginx
echo "installed $OUT ($n ranges); confirm real IPs in /var/log/nginx/access.log"
