#!/usr/bin/env python3
"""Build the AI Threat Engine thesis presentation (.pptx).

Run:  ./ai_threat_engine_starter/venv/bin/python3 A_presentation/make_ppt.py
Requires: python-pptx, images/ generated by make_images.py
"""
import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

HERE = os.path.dirname(os.path.abspath(__file__))
IMG  = os.path.join(HERE, "images")

# ---- palette ----
BG      = RGBColor(0x0B, 0x0E, 0x1A)
PANEL   = RGBColor(0x14, 0x1A, 0x30)
CYAN    = RGBColor(0x22, 0xD3, 0xEE)
VIOLET  = RGBColor(0xA7, 0x8B, 0xFA)
MAGENTA = RGBColor(0xF4, 0x72, 0xB6)
GREEN   = RGBColor(0x34, 0xD3, 0x99)
AMBER   = RGBColor(0xFB, 0xBF, 0x24)
RED     = RGBColor(0xFB, 0x71, 0x85)
TEXT    = RGBColor(0xE8, 0xEC, 0xF8)
SOFT    = RGBColor(0x9A, 0xA6, 0xC4)
TEXT_DIM = RGBColor(0x58, 0x62, 0x7E)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

prs = Presentation()
prs.slide_width  = SLIDE_W
prs.slide_height = SLIDE_H
BLANK = prs.slide_layouts[6]

ACCENTS = [CYAN, VIOLET, MAGENTA, GREEN, AMBER]


_page = [0]  # running slide counter for footers


def add_slide(accent=CYAN, footer=True):
    _page[0] += 1
    s = prs.slides.add_slide(BLANK)
    s.background.fill.solid()
    s.background.fill.fore_color.rgb = BG
    # left accent bar
    bar = s.shapes.add_shape(1, 0, 0, Inches(0.14), SLIDE_H)
    bar.fill.solid(); bar.fill.fore_color.rgb = accent
    bar.line.fill.background()
    # bottom hairline
    hl = s.shapes.add_shape(1, Inches(0.14), SLIDE_H - Emu(19050), SLIDE_W, Emu(19050))
    hl.fill.solid(); hl.fill.fore_color.rgb = PANEL
    hl.line.fill.background()
    if footer:
        # name bottom-left, slide number bottom-right
        fl = s.shapes.add_textbox(Inches(0.5), SLIDE_H - Inches(0.42), Inches(6), Inches(0.32))
        p = fl.text_frame.paragraphs[0]; r = p.add_run()
        r.text = "AI Threat Engine · Diana Maria Secarea"
        r.font.size = Pt(9); r.font.color.rgb = TEXT_DIM
        fr = s.shapes.add_textbox(SLIDE_W - Inches(1.3), SLIDE_H - Inches(0.42), Inches(0.9), Inches(0.32))
        p2 = fr.text_frame.paragraphs[0]; p2.alignment = PP_ALIGN.RIGHT
        r2 = p2.add_run(); r2.text = str(_page[0]).zfill(2)
        r2.font.size = Pt(9); r2.font.color.rgb = accent; r2.font.bold = True
    return s


def divider(main, accent, kicker, num):
    """Full-bleed section divider slide."""
    s = add_slide(accent, footer=False)
    band = s.shapes.add_shape(1, 0, 0, Inches(0.14), SLIDE_H)
    band.fill.solid(); band.fill.fore_color.rgb = accent; band.line.fill.background()
    txt(s, Inches(1.0), Inches(2.5), Inches(2.4), Inches(1.6),
        [(num, accent, True)], size=90)
    tb = s.shapes.add_textbox(Inches(3.4), Inches(2.75), Inches(9.0), Inches(2.2))
    tf = tb.text_frame; tf.word_wrap = True
    p0 = tf.paragraphs[0]; r0 = p0.add_run(); r0.text = kicker
    r0.font.size = Pt(15); r0.font.color.rgb = SOFT; r0.font.name = "Segoe UI"
    p1 = tf.add_paragraph(); r1 = p1.add_run(); r1.text = main
    r1.font.size = Pt(46); r1.font.bold = True; r1.font.color.rgb = TEXT; r1.font.name = "Segoe UI"
    return s


def txt(slide, x, y, w, h, runs, size=18, bold=False, color=TEXT,
        align=PP_ALIGN.LEFT, font="Segoe UI", spacing=1.0):
    """runs: str OR list of (text, color, bold) tuples for one paragraph each."""
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    if isinstance(runs, str):
        runs = [(runs, color, bold)]
    for i, item in enumerate(runs):
        t, c, b = item if isinstance(item, tuple) else (item, color, bold)
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = spacing
        r = p.add_run(); r.text = t
        r.font.size = Pt(size); r.font.bold = b
        r.font.color.rgb = c; r.font.name = font
    return tb


def bullets(slide, x, y, w, h, items, size=16, gap=6):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame; tf.word_wrap = True
    for i, item in enumerate(items):
        head, body, col = item
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(gap); p.line_spacing = 1.08
        r = p.add_run(); r.text = "▸ "
        r.font.size = Pt(size); r.font.color.rgb = col; r.font.bold = True
        r2 = p.add_run(); r2.text = head
        r2.font.size = Pt(size); r2.font.color.rgb = col; r2.font.bold = True
        if body:
            r3 = p.add_run(); r3.text = " — " + body
            r3.font.size = Pt(size); r3.font.color.rgb = TEXT
    return tb


def title(slide, main, accent_word=None, accent=CYAN, sub=None):
    tb = slide.shapes.add_textbox(Inches(0.55), Inches(0.32), Inches(12.3), Inches(1.1))
    tf = tb.text_frame; tf.word_wrap = True
    p = tf.paragraphs[0]
    r = p.add_run(); r.text = main + (" " if accent_word else "")
    r.font.size = Pt(32); r.font.bold = True; r.font.color.rgb = TEXT
    r.font.name = "Segoe UI"
    if accent_word:
        r2 = p.add_run(); r2.text = accent_word
        r2.font.size = Pt(32); r2.font.bold = True; r2.font.color.rgb = accent
        r2.font.name = "Segoe UI"
    if sub:
        p2 = tf.add_paragraph()
        r3 = p2.add_run(); r3.text = sub
        r3.font.size = Pt(14); r3.font.color.rgb = SOFT; r3.font.italic = True


def chip(slide, x, y, text, color, size=12):
    w = Inches(0.28 + len(text) * 0.085)
    sh = slide.shapes.add_shape(9, x, y, w, Inches(0.42))  # rounded rect
    sh.fill.solid(); sh.fill.fore_color.rgb = PANEL
    sh.line.color.rgb = color; sh.line.width = Pt(1.4)
    tf = sh.text_frame; tf.word_wrap = False
    p = tf.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
    r = p.add_run(); r.text = text
    r.font.size = Pt(size); r.font.bold = True; r.font.color.rgb = color
    return x + w + Inches(0.18)


def pic(slide, name, x, y, w=None, h=None):
    return slide.shapes.add_picture(os.path.join(IMG, name), x, y, width=w, height=h)


def notes(slide, text):
    slide.notes_slide.notes_text_frame.text = text


def stat_card(slide, x, y, w, num, label, color):
    card = slide.shapes.add_shape(9, x, y, w, Inches(1.5))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = color; card.line.width = Pt(1.6)
    tf = card.text_frame
    p = tf.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
    r = p.add_run(); r.text = num
    r.font.size = Pt(30); r.font.bold = True; r.font.color.rgb = color
    p2 = tf.add_paragraph(); p2.alignment = PP_ALIGN.CENTER
    r2 = p2.add_run(); r2.text = label
    r2.font.size = Pt(11); r2.font.color.rgb = SOFT


# ======================================================================
# SLIDE 1 — Title
# ======================================================================
s = add_slide(MAGENTA, footer=False)
txt(s, Inches(0.8), Inches(0.7), Inches(11.7), Inches(0.5),
    [("BUCHAREST UNIVERSITY OF ECONOMIC STUDIES · CYBERNETICS, STATISTICS & ECONOMIC INFORMATICS", SOFT, False)], size=12)
txt(s, Inches(0.8), Inches(1.55), Inches(11.9), Inches(1.7),
    [("Architecture and Evaluation of a SIEM Integrating", TEXT, True),
     ("Unsupervised Anomaly Detection and Knowledge-Grounded Language Models", CYAN, True)], size=30, spacing=1.05)
txt(s, Inches(0.8), Inches(3.6), Inches(11.7), Inches(0.6),
    [("An AI Threat Engine on Wazuh — anomaly ensemble · hybrid RAG · agentic CVE ingestion · fully local, fully auditable", SOFT, False)], size=16)
x = Inches(0.8)
for c, t in [(GREEN, "F1 89.2%"), (CYAN, "RECALL 95.9%"), (VIOLET, "1,333 VECTORS"),
             (AMBER, "CITATIONS 98.3%"), (MAGENTA, "100% LOCAL")]:
    x = chip(s, x, Inches(4.5), t, c)
txt(s, Inches(0.8), Inches(6.05), Inches(11.7), Inches(0.9),
    [("Graduate: Secărea Diana Maria", TEXT, True),
     ("Coordinator: prof. univ. dr. Cătălin Boja  ·  Bucharest 2026", SOFT, False)], size=15)
notes(s, "Good morning. My thesis is titled 'Architecture and Evaluation of a SIEM Integrating Unsupervised Anomaly "
         "Detection and Knowledge-Grounded Language Models'. In practice it is an AI Threat Engine that upgrades the "
         "open-source Wazuh SIEM with three AI layers: an unsupervised anomaly-detection ensemble, a retrieval-"
         "augmented LLM analyst, and an autonomous CVE-ingestion agent. Everything runs locally — no cloud APIs, no "
         "data leaves the machine. Headline numbers: F1 89.2%, attack recall 95.9%, 98.3% citation precision.")

# ======================================================================
# SLIDE 2 — Agenda / roadmap
# ======================================================================
s = add_slide(VIOLET)
title(s, "Roadmap —", "the loop we'll walk through", VIOLET,
      "detection tells you WHAT · RAG explains WHY · the agent keeps knowledge CURRENT")
steps = [
    ("01", "The problem", "rule-based SIEMs can't score, explain, or self-update", RED),
    ("02", "Machine learning", "16 features → dual-model ensemble → tiered verdict", GREEN),
    ("03", "Retrieval-augmented generation", "grounded, cited explanations from a local LLM", CYAN),
    ("04", "Agentic CVE ingestion", "the knowledge base maintains itself", AMBER),
    ("05", "Evaluation & live demo", "reproducible metrics + the system running", MAGENTA),
]
y = Inches(1.75)
for num, head, body, col in steps:
    card = s.shapes.add_shape(9, Inches(0.7), y, Inches(11.9), Inches(0.92))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = col; card.line.width = Pt(1.4)
    tf = card.text_frame; tf.word_wrap = True
    tf.margin_left = Inches(0.25); tf.margin_top = Inches(0.14)
    p = tf.paragraphs[0]
    r = p.add_run(); r.text = num + "   "
    r.font.size = Pt(20); r.font.bold = True; r.font.color.rgb = col; r.font.name = "Consolas"
    r2 = p.add_run(); r2.text = head + "   "
    r2.font.size = Pt(17); r2.font.bold = True; r2.font.color.rgb = TEXT
    r3 = p.add_run(); r3.text = "— " + body
    r3.font.size = Pt(13.5); r3.font.color.rgb = SOFT
    y += Inches(1.02)
notes(s, "Here's the roadmap. First the problem with rule-based SIEMs. Then the three AI contributions in order: the "
         "machine-learning ensemble that scores every alert, the retrieval-augmented generation layer that explains "
         "and cites, and the agentic component that keeps the knowledge base current. Finally, evaluation and a live "
         "demo. The through-line: detection tells you WHAT is anomalous, RAG explains WHY, and the agent keeps the "
         "knowledge CURRENT — a closed loop.")

# ======================================================================
# SLIDE 3 — Motivation
# ======================================================================
s = add_slide(CYAN)
title(s, "Motivation — why add", "AI to a SIEM?", CYAN)
bullets(s, Inches(0.65), Inches(1.5), Inches(7.0), Inches(5.2), [
    ("Alert fatigue is real", "a single host produces thousands of alerts/day; analysts triage a fraction", RED),
    ("Rules only catch what they name", "signature rules miss novel behavior and low-and-slow attacks", AMBER),
    ("Severity ≠ maliciousness", "Wazuh level 5 can be routine OR the start of a brute force — context decides", VIOLET),
    ("Knowledge is scattered", "MITRE, Sigma, CVEs, internal runbooks — nobody can hold it all in their head", CYAN),
    ("SOC expertise is expensive", "an explainable AI layer lets one analyst do the work of a tier-1 team", GREEN),
], size=16)
stat_card(s, Inches(8.1), Inches(1.7), Inches(4.4), "2,171", "ALERTS IN STUDY CORPUS", CYAN)
stat_card(s, Inches(8.1), Inches(3.4), Inches(4.4), "640", "ATTACK ALERTS (14 FAMILIES)", RED)
stat_card(s, Inches(8.1), Inches(5.1), Inches(4.4), "0", "LABELS NEEDED FOR TRAINING", GREEN)
notes(s, "Why does a SIEM need AI? Four problems: alert fatigue — analysts drown in noise; rules only detect what "
         "they explicitly name; severity levels don't measure maliciousness; and the knowledge needed to respond is "
         "scattered across MITRE, Sigma, CVE feeds and internal documents. The engine addresses each: anomaly "
         "scoring prioritizes, unsupervised learning needs zero labels, and RAG unifies the knowledge.")

# ======================================================================
# SLIDE 3 — Wazuh integration
# ======================================================================
s = add_slide(AMBER)
title(s, "Integration with", "Wazuh", AMBER, "non-invasive: Wazuh is never modified — the engine reads alongside it")
bullets(s, Inches(0.65), Inches(1.6), Inches(12.2), Inches(2.7), [
    ("Tap point: alerts.json", "the engine tails /var/ossec/logs/alerts/alerts.json in real time (read-only, wazuh group)", AMBER),
    ("Every alert scored in ~12 ms", "feature extraction → ensemble → combined score + label attached to the alert", GREEN),
    ("Daily collector + cron", "collect_training_data.py snapshots alerts for continuous retraining data", CYAN),
    ("Flask API layer", "/api/alerts/scored, /api/chat, /api/knowledge/upload — dashboard and chat consume these", VIOLET),
    ("Wazuh metadata becomes features", "rule.level, rule.id, groups, MITRE tags feed the ML — the engine builds ON Wazuh's parsing", MAGENTA),
], size=15)
pic(s, "injection.png", Inches(2.1), Inches(4.15), w=Inches(9.2))
notes(s, "Integration is deliberately non-invasive. Wazuh keeps doing what it does; the engine tails alerts.json "
         "read-only. Each new alert is scored in about 12 milliseconds and the verdict flows to three consumers: "
         "the dashboard sorts by score, the chat injects the verdict into LLM context, and low-level NORMAL alerts "
         "gate threat-intel retrieval so the LLM never invents attack stories about routine logins.")

# ======================================================================
# SLIDE 4 — Technologies
# ======================================================================
s = add_slide(VIOLET)
title(s, "Technology", "Stack", VIOLET, "every component is open-source and runs on one machine")
cols = [
    ("MACHINE LEARNING", GREEN, ["scikit-learn (IF + MLP AE)", "NumPy · joblib", "StandardScaler pipeline", "custom feature extractor"]),
    ("RAG & LLM", CYAN, ["Ollama · llama3.2 (local)", "Qdrant vector DB (Docker)", "sentence-transformers (dense)", "fastembed BM25 (sparse)"]),
    ("DATA & BACKEND", AMBER, ["PostgreSQL (ledger/audit)", "Flask + SSE streaming", "Docker Compose", "Python 3.13"]),
    ("SECURITY BASE", MAGENTA, ["Wazuh 4.14 Manager", "MITRE ATT&CK · D3FEND", "Sigma · CISA KEV · CIS", "NVD / OTX feeds"]),
]
x = Inches(0.6)
for name, col, items in cols:
    card = s.shapes.add_shape(9, x, Inches(1.7), Inches(2.95), Inches(4.6))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = col; card.line.width = Pt(1.8)
    tf = card.text_frame; tf.word_wrap = True
    tf.margin_left = Inches(0.18); tf.margin_top = Inches(0.2)
    p = tf.paragraphs[0]
    r = p.add_run(); r.text = name
    r.font.size = Pt(15); r.font.bold = True; r.font.color.rgb = col
    for it in items:
        pp = tf.add_paragraph(); pp.space_before = Pt(9)
        rr = pp.add_run(); rr.text = "• " + it
        rr.font.size = Pt(13.5); rr.font.color.rgb = TEXT
    x += Inches(3.1)
txt(s, Inches(0.65), Inches(6.55), Inches(12), Inches(0.5),
    [("Zero cloud dependencies → suitable for air-gapped SOCs, no per-token cost, GDPR-safe by construction", SOFT, False)],
    size=14)
notes(s, "The stack: scikit-learn for both models — Isolation Forest and an MLPRegressor autoencoder. RAG runs on "
         "Qdrant with dual embeddings — dense sentence-transformers plus sparse BM25. The LLM is llama3.2 served by "
         "Ollama, fully local. PostgreSQL keeps the audit ledger. The key property: zero cloud dependencies — "
         "deployable in air-gapped environments with no per-token cost.")

# ======================================================================
# DIVIDER — Part One: Machine Learning
# ======================================================================
divider("Machine Learning", GREEN, "PART ONE · unsupervised anomaly detection", "01")

# ======================================================================
# SLIDE 5 — ML overview: training pipeline (unsupervised)
# ======================================================================
s = add_slide(GREEN)
title(s, "Training Pipeline —", "unsupervised by design", GREEN,
      "no human ever labels an alert; the models learn 'normal' from the environment itself")
pic(s, "training.png", Inches(1.5), Inches(1.55), w=Inches(10.3))
bullets(s, Inches(0.75), Inches(6.15), Inches(12.0), Inches(1.2), [
    ("IF: contamination='auto'", "fitted on all 2,171 alerts, no label filter — makes no assumption about the anomaly proportion", GREEN),
    ("AE: iterative trimming ×3", "~30% attacks left in on purpose; train → drop top-25% recon errors → drop 15% → final clean fit", VIOLET),
], size=14)
notes(s, "The training strategy is fully unsupervised — this is the methodological core of the thesis. Raw alerts, "
         "including the attacks hiding among them, flow through feature extraction and scaling. The Isolation Forest "
         "trains with contamination='auto' on all 2,171 alerts with no label filter — it makes no assumption about "
         "the anomaly proportion. The autoencoder deliberately leaves about 30% attacks mixed in, then uses "
         "iterative trimming: train, discard the worst-reconstructed 25%, retrain, discard 15%, then a final fit on "
         "the cleaned set. Without trimming the autoencoder would learn to reconstruct attacks too. No labels at any "
         "stage — the literature calls this self-supervised one-class classification. Operationally: deploy on a "
         "network you've never seen and it learns that network's normal by itself.")

# ======================================================================
# SLIDE 6 — Feature engineering
# ======================================================================
s = add_slide(CYAN)
title(s, "Feature Engineering —", "16 signals per alert", CYAN,
      "domain knowledge distilled into numbers: content, time, network, identity, Wazuh metadata")
pic(s, "features.png", Inches(0.9), Inches(1.6), w=Inches(11.5))
txt(s, Inches(0.9), Inches(6.5), Inches(11.8), Inches(0.8),
    [("Iterated 14× against real attack simulations — e.g. MITRE-tag count was REMOVED after it caused false alarms "
      "(Wazuh tags benign SSH logins with T1078), and Cloudflare CDN ranges are excluded from the external-IP flag.", SOFT, False)],
    size=13)
notes(s, "Each alert becomes a 16-dimensional vector. Content features like failed-login counts; temporal features "
         "like off-hours activity; network features — external source IP with CDN awareness; identity features like "
         "privileged account changes; and Wazuh metadata. The set was refined 14 times against attack simulations. "
         "A key lesson: I REMOVED the MITRE-tag-count feature because Wazuh attaches MITRE tags to benign events, "
         "which poisoned the feature. Feature engineering is iterative and empirical, not guesswork.")

# ======================================================================
# SLIDE 7 — Isolation Forest
# ======================================================================
s = add_slide(GREEN)
title(s, "Algorithm 1 —", "Isolation Forest", GREEN)
bullets(s, Inches(0.65), Inches(1.55), Inches(6.6), Inches(4.6), [
    ("Core idea", "anomalies are FEW and DIFFERENT → random splits isolate them in short paths", GREEN),
    ("Score", "path length → anomaly score, calibrated min-max → 0-100 scale", CYAN),
    ("Threshold", "50 = 90th percentile of clean scores (score-based, not model.predict)", AMBER),
    ("Why chosen", "no labels needed · handles mixed feature scales · fast (µs/alert) · robust to irrelevant features", VIOLET),
    ("Weakness", "axis-parallel splits miss subtle multivariate correlations → that's what the AE covers", RED),
], size=15)
pic(s, "separation.png", Inches(7.35), Inches(1.9), w=Inches(5.6))
txt(s, Inches(7.35), Inches(5.9), Inches(5.6), Inches(0.9),
    [("75.1-point separation between attack (92.4) and clean (17.3) average scores", SOFT, False)], size=13)
notes(s, "First ensemble member: Isolation Forest. The intuition — anomalies are few and different, so random "
         "splits isolate them quickly; short isolation path = high anomaly score. I calibrate raw scores to 0-100 "
         "and set the threshold at the 90th percentile of clean scores. Why this algorithm? It needs no labels, "
         "it's extremely fast, and it's robust to noisy features. Its weakness — axis-parallel splits miss subtle "
         "feature correlations — is exactly what the second model compensates for. Note the 75-point score "
         "separation: attacks average 92, normal traffic 17.")

# ======================================================================
# SLIDE 8 — Autoencoder
# ======================================================================
s = add_slide(VIOLET)
title(s, "Algorithm 2 —", "Autoencoder", VIOLET)
bullets(s, Inches(0.65), Inches(1.55), Inches(6.9), Inches(4.8), [
    ("Architecture", "16 → 8 → 4 → 8 → 16 bottleneck MLP (sklearn MLPRegressor)", VIOLET),
    ("Core idea", "trained to reconstruct NORMAL alerts; attacks reconstruct badly → high MSE = anomaly", CYAN),
    ("The 4-dim bottleneck", "forces the net to learn the compressed manifold of normal behavior", MAGENTA),
    ("Why chosen", "captures nonlinear feature CORRELATIONS the forest can't · complementary error profile", GREEN),
    ("Training", "self-supervised — the input is its own target; iterative trimming purifies the data", AMBER),
], size=15)
# small architecture visual made of shapes
xs = [7.9, 8.9, 9.8, 10.7, 11.7]
hs = [2.6, 1.7, 1.0, 1.7, 2.6]
lbl = ["16", "8", "4", "8", "16"]
for i, (xx, hh) in enumerate(zip(xs, hs)):
    sh = s.shapes.add_shape(9, Inches(xx), Inches(2.6 + (2.6 - hh) / 2), Inches(0.62), Inches(hh))
    sh.fill.solid(); sh.fill.fore_color.rgb = PANEL
    col = MAGENTA if i == 2 else VIOLET
    sh.line.color.rgb = col; sh.line.width = Pt(2)
    tf = sh.text_frame; p = tf.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
    r = p.add_run(); r.text = lbl[i]; r.font.size = Pt(14); r.font.bold = True; r.font.color.rgb = col
txt(s, Inches(7.9), Inches(5.6), Inches(4.6), Inches(0.5),
    [("encoder  →  bottleneck  →  decoder", SOFT, False)], size=13, align=PP_ALIGN.CENTER)
txt(s, Inches(7.6), Inches(6.15), Inches(5.2), Inches(0.9),
    [("reconstruction error (MSE) = anomaly score", CYAN, True)], size=15, align=PP_ALIGN.CENTER)
notes(s, "Second member: an autoencoder — a bottleneck network 16-8-4-8-16 trained to reconstruct its own input. "
         "It only ever sees normal alerts (after iterative trimming), so it learns the compressed manifold of "
         "normality. When an attack arrives, reconstruction fails and the MSE spikes. The 4-neuron bottleneck is "
         "the point: it forces compression, so the network must learn correlations BETWEEN features — precisely "
         "what Isolation Forest's axis-parallel splits cannot capture. The two models fail differently, which is "
         "the whole argument for the ensemble.")

# ======================================================================
# SLIDE 9 — Ensemble
# ======================================================================
s = add_slide(RED)
title(s, "The Ensemble —", "fusion & label logic", RED,
      "the ensemble is a fixed scoring layer, not a trained model — only IF and AE are trained")
pic(s, "ensemble.png", Inches(1.6), Inches(1.55), w=Inches(10.1))
notes(s, "The ensemble combines both verdicts. Crucially, the TIER is decided by the two models' BINARY anomaly "
         "decisions, not their continuous scores — this preserves each model's calibrated threshold rather than "
         "inventing a new one in the combination layer. Both flag → CRITICAL; only the autoencoder → HIGH (the "
         "higher-precision model); only the forest → POSSIBLE, dampened ×0.65; neither → NORMAL. The displayed "
         "combined score is a weighted average, 0.45 × IF + 0.55 × AE. The ensemble itself is NOT trained — it's a "
         "deterministic fusion layer, which keeps it explainable. The security argument: to evade detection an "
         "attacker must simultaneously fool tree-based isolation AND a neural reconstruction manifold — and those "
         "evasion strategies are contradictory, so a simple attack cannot beat both. Note the honest caveat: on the "
         "current evaluation set the AE-only HIGH tier is empty, so the AE's value here is precision, not extra recall.")

# ======================================================================
# SLIDE 10 — Scores into system & RAG
# ======================================================================
s = add_slide(CYAN)
title(s, "From Score to", "Action — injection into system & RAG", CYAN)
bullets(s, Inches(0.65), Inches(1.55), Inches(12.2), Inches(3.0), [
    ("Dashboard", "every streamed alert carries combined_score + label; UI sorts HIGH first, benign-rule exceptions zero the score", MAGENTA),
    ("Chat grounding", "matched alerts enter the LLM prompt WITH their ML verdict: 'rule 5720 · level 10 · Anomaly HIGH (94/100)'", VIOLET),
    ("Retrieval gating", "if all matched alerts are level < 5, threat-intel retrieval is SKIPPED and the LLM is told not to map to ATT&CK", CYAN),
    ("Label → language", "CRITICAL/HIGH/POSSIBLE/NORMAL is the shared vocabulary between ML, API, UI and LLM — one verdict everywhere", GREEN),
    ("Analyst feedback loop", "user-defined benign rules & suspicious groups adjust scoring live, no retrain needed", AMBER),
], size=15)
pic(s, "injection.png", Inches(2.3), Inches(4.55), w=Inches(8.7))
notes(s, "How do scores reach the rest of the system? Three paths. The dashboard receives every alert with its "
         "combined score and label, sorted worst-first. The chat pipeline injects the ML verdict directly into the "
         "LLM's context — the model literally reads 'Anomaly HIGH, 94 out of 100' next to each alert. And scores "
         "gate retrieval: for low-level NORMAL events we skip threat-intel entirely and instruct the LLM not to "
         "invent attack narratives. This anti-hallucination gating came from a real failure mode I observed.")

# ======================================================================
# SLIDE 11 — ML evaluation
# ======================================================================
s = add_slide(GREEN)
title(s, "Detection", "Evaluation", GREEN, "2,171 alerts · 1,531 clean · 640 attack across 14 simulated attack families")
pic(s, "confusion.png", Inches(0.7), Inches(1.7), w=Inches(5.7))
pic(s, "metrics.png", Inches(6.7), Inches(1.7), w=Inches(6.1))
txt(s, Inches(0.75), Inches(6.35), Inches(12.2), Inches(0.9),
    [("100% detection: SSH brute force · web attacks (SQLi, XSS) · C2 & DNS exfil · reverse shells · rootkits · account manipulation.  "
      "Hardest case: single failed PAM logins (45%) — informationally identical to a typo → future work: temporal window features.",
      SOFT, False)], size=13)
notes(s, "Evaluation on 2,171 alerts: precision 83.4%, recall 95.9%, F1 89.2%, false-positive rate 8%. The "
         "confusion matrix: 614 attacks caught, only 26 missed. Entire attack families are at 100% — brute force, "
         "web attacks, C2, reverse shells, rootkits. I'm transparent about the failure case: single failed PAM "
         "logins are only caught 45% of the time — a lone failed login is informationally identical to a typo. "
         "The fix is temporal aggregation features, which I discuss under future work.")

# ======================================================================
# DIVIDER — Part Two: Retrieval-Augmented Generation
# ======================================================================
divider("Retrieval-Augmented Generation", CYAN, "PART TWO · grounded, cited explanations", "02")

# ======================================================================
# SLIDE 12 — RAG: why it explains
# ======================================================================
s = add_slide(VIOLET)
title(s, "RAG — the analyst that", "explains", VIOLET,
      "detection says WHAT is anomalous; retrieval-augmented generation explains WHY and WHAT TO DO")
bullets(s, Inches(0.65), Inches(1.6), Inches(12.2), Inches(4.6), [
    ("The problem with raw LLMs", "hallucination — a bare LLM will invent techniques, CVEs and IPs that don't exist", RED),
    ("The RAG answer", "retrieve verified knowledge first, then force the LLM to answer FROM it, with citations [1]-[n]", VIOLET),
    ("Two grounding sources", "1,333-point threat-intel base (MITRE·Sigma·KEV·CIS·docs) + the live Wazuh alert stream", CYAN),
    ("ML verdicts in the loop", "anomaly labels ride along with every alert the LLM sees — detection and explanation stay consistent", GREEN),
    ("User documents quoted verbatim", "uploaded runbooks are chunked & indexed; the analyst quotes them word-for-word with the document title", MAGENTA),
    ("Session memory", "multi-turn conversations with per-session history — analysts can drill down naturally", AMBER),
], size=15)
notes(s, "Detection tells you WHAT is anomalous. RAG explains WHY and what to do about it. A bare LLM hallucinates "
         "— it will happily invent CVE numbers. RAG fixes this by retrieving verified knowledge first and forcing "
         "the model to answer from it with numbered citations. Grounding comes from two sources: the threat-intel "
         "knowledge base and the live alert stream — with ML verdicts attached. Uploaded runbooks are quoted "
         "verbatim with the document title, so institutional knowledge becomes part of every answer.")

# ======================================================================
# SLIDE 13 — Vector DB
# ======================================================================
s = add_slide(CYAN)
title(s, "Building the", "Vector Database", CYAN,
      "every knowledge item → one 'episode' → dense vector + sparse vector + payload in Qdrant")
pic(s, "hybrid_rag.png", Inches(1.3), Inches(1.5), w=Inches(10.7))
notes(s, "The knowledge base construction: every item — a MITRE technique, a Sigma rule, a KEV entry, a document "
         "chunk — becomes an 'episode' with a summary, tags and entities. Each episode is embedded TWICE: a "
         "384-dimensional dense vector for semantic meaning, and a sparse BM25 vector for exact keywords. At query "
         "time both retrievers fetch 40 candidates each and Reciprocal Rank Fusion merges the rankings — normalized "
         "to [0,1]. Why hybrid? Security queries are bimodal: 'CVE-2021-44228' needs exact matching, while 'is "
         "someone stealing data' needs semantics. RRF gets both without tuning weights.")

# ======================================================================
# SLIDE 14 — PostgreSQL
# ======================================================================
s = add_slide(AMBER)
title(s, "PostgreSQL —", "the system's memory & conscience", AMBER,
      "vectors answer 'what is similar?' — Postgres answers 'what happened, when, and why?'")
rows = [
    ("threat_intel", "relational mirror of every indexed knowledge item (incl. user uploads) — joinable, queryable", CYAN),
    ("cve_decisions", "one row per CVE the agent ever judged: base score, boost, final, decision, LLM reasoning", GREEN),
    ("ingestion_log", "one row per agent run: cursor used, rollup counts, status — full run traceability", VIOLET),
    ("pending_review view", "the 4-6 quarantine queue an analyst reviews — the human-in-the-loop surface", AMBER),
]
y = Inches(1.75)
for name, desc, col in rows:
    card = s.shapes.add_shape(9, Inches(0.7), y, Inches(11.9), Inches(1.02))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = col; card.line.width = Pt(1.5)
    tf = card.text_frame; tf.word_wrap = True
    tf.margin_left = Inches(0.25); tf.margin_top = Inches(0.12)
    p = tf.paragraphs[0]
    r = p.add_run(); r.text = name + "   "
    r.font.size = Pt(16); r.font.bold = True; r.font.color.rgb = col; r.font.name = "Consolas"
    r2 = p.add_run(); r2.text = desc
    r2.font.size = Pt(14); r2.font.color.rgb = TEXT
    y += Inches(1.16)
txt(s, Inches(0.7), Inches(6.45), Inches(12), Inches(0.7),
    [("Design principle: Qdrant is disposable (re-indexable), Postgres is the source of truth — every automated decision is auditable and reversible.", SOFT, False)],
    size=14)
notes(s, "Why Postgres next to a vector DB? Different questions. Qdrant answers 'what is similar' — Postgres "
         "answers 'what happened and why'. Four structures: threat_intel mirrors every indexed item relationally; "
         "cve_decisions records every judgment the agent ever made including the LLM's reasoning; ingestion_log "
         "gives per-run traceability; and the pending_review view is the human-in-the-loop surface. The design "
         "principle: the vector index is disposable and re-buildable — Postgres is the permanent source of truth.")

# ======================================================================
# SLIDE 15 — Grounded answer generation
# ======================================================================
s = add_slide(MAGENTA)
title(s, "Answer Generation with", "grounded knowledge", MAGENTA)
# prompt anatomy panel
card = s.shapes.add_shape(9, Inches(0.65), Inches(1.6), Inches(6.3), Inches(5.3))
card.fill.solid(); card.fill.fore_color.rgb = PANEL
card.line.color.rgb = MAGENTA; card.line.width = Pt(1.5)
tf = card.text_frame; tf.word_wrap = True
tf.margin_left = Inches(0.25); tf.margin_top = Inches(0.2)
lines = [
    ("PROMPT ANATOMY", MAGENTA, True, 15),
    ("SYSTEM: analyst persona + citation rules", CYAN, False, 13),
    ("  + anti-hallucination: low-level NORMAL alerts", SOFT, False, 12),
    ("    must NOT be mapped to attack techniques", SOFT, False, 12),
    ("  + quote user documents verbatim, cite [n]", SOFT, False, 12),
    ("=== Threat Intelligence Context ===", AMBER, True, 13),
    ("  [1]-[5] retrieved episodes (RRF top-5)", TEXT, False, 12),
    ("=== Wazuh Alert Logs (matches) ===", AMBER, True, 13),
    ("  alerts + ensemble verdicts (HIGH 94/100)", TEXT, False, 12),
    ("USER: the analyst's question", GREEN, True, 13),
    ("→ llama3.2 · streamed via SSE, token by token", VIOLET, False, 13),
]
for i, (t, c, b, sz) in enumerate(lines):
    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
    p.space_after = Pt(5)
    r = p.add_run(); r.text = t
    r.font.size = Pt(sz); r.font.bold = b; r.font.color.rgb = c; r.font.name = "Consolas"
bullets(s, Inches(7.3), Inches(1.7), Inches(5.6), Inches(5.2), [
    ("Level-gated retrieval", "intel only fetched when an alert is level ≥ 5", CYAN),
    ("Citations enforced", "[n] markers verified against sources in eval", GREEN),
    ("Sources returned to UI", "every reply ships its evidence chips", VIOLET),
    ("Refusal is a feature", "no evidence → say so, never invent", AMBER),
    ("Streaming UX", "SSE tokens — answers appear as they're generated", MAGENTA),
], size=14)
notes(s, "The prompt is assembled in layers: a system prompt with the analyst persona, citation rules, and two "
         "anti-hallucination guards — never map routine events to attack techniques, and quote user documents "
         "verbatim. Then the retrieved intel block, numbered 1 to 5; then matched alerts WITH their ensemble "
         "verdicts; finally the user's question. Answers stream token-by-token over SSE, and each reply returns "
         "its sources so the UI shows evidence chips. Crucially, refusal is a feature — when there's no evidence, "
         "the model says so.")

# ======================================================================
# SLIDE 16 — RAG evaluation
# ======================================================================
s = add_slide(GREEN)
title(s, "Evaluating the", "RAG — two stages", GREEN,
      "retrieval quality and generation quality are different failure modes — measure both")
pic(s, "rag_eval.png", Inches(0.85), Inches(1.6), w=Inches(11.6))
txt(s, Inches(0.85), Inches(6.35), Inches(11.8), Inches(0.9),
    [("Honest findings: cross-encoder reranking HURT domain retrieval (removed) · weak categories identified (APT, C2 recall) · "
      "over-refusal regex flagged 8/35 but manual verification showed 0 true refusals — metrics need human validation.", SOFT, False)],
    size=13)
notes(s, "RAG evaluation runs in two stages because retrieval and generation fail differently. Retrieval on 82 "
         "queries: hit rate 82.9%, MRR 0.695. Generation on 35 queries with an LLM judge: faithfulness 0.71, "
         "citation precision 98.3% — when the model cites source 3, source 3 really supports the claim. I report "
         "negative results too: cross-encoder reranking actually hurt domain retrieval so I removed it, and the "
         "over-refusal metric needed manual verification — the regex flagged 8 cases but human inspection confirmed "
         "zero true refusals. Metrics without validation lie.")

# ======================================================================
# DIVIDER — Part Three: Agentic Ingestion
# ======================================================================
divider("Agentic CVE Ingestion", AMBER, "PART THREE · the knowledge base maintains itself", "03")

# ======================================================================
# SLIDE 17 — Agentic CVE workflow
# ======================================================================
s = add_slide(AMBER)
title(s, "Agentic Workflow —", "autonomous CVE ingestion", AMBER,
      "the knowledge base updates itself daily — with bounded reasoning and full audit")
pic(s, "agent.png", Inches(1.15), Inches(1.5), w=Inches(11.0))
txt(s, Inches(0.85), Inches(6.35), Inches(11.8), Inches(0.9),
    [("Design: fixed control flow, ONE bounded LLM step (relevance 0-10) · environment boost from local rules & alert history · "
      "LLM failure → conservative score 5 → review queue, never silent drop · duplicates skipped against the Postgres ledger.", SOFT, False)],
    size=13)
notes(s, "The agentic component: a scheduled agent that keeps the knowledge base current. Daily: fetch new CVEs "
         "from NVD and CISA-KEV, dedup against the ledger, add an environment boost — if the CVE touches software "
         "we actually run or matches our alert history — then ONE bounded LLM call scores relevance 0 to 10. "
         "Three bands: 7+ auto-indexes into RAG, 4-6 quarantines for human review, below 4 drops with logged "
         "reasoning. The design philosophy: agentic doesn't mean unbounded — fixed control flow, one LLM decision, "
         "every outcome auditable and reversible. If the LLM is down, CVEs route to review — fail-safe, not silent.")

# ======================================================================
# SLIDE 18 — Full architecture
# ======================================================================
s = add_slide(CYAN)
title(s, "The Whole System —", "architecture", CYAN)
pic(s, "architecture.png", Inches(1.35), Inches(1.45), w=Inches(10.6))
notes(s, "Everything together. Four layers. Data sources: Wazuh alerts, CVE feeds, threat-intel corpora, user "
         "documents. AI core: feature extraction into the anomaly ensemble, the CVE agent, and the local LLM. "
         "Storage: Qdrant for similarity, Postgres for truth. Interfaces: the live dashboard and the RAG chat "
         "analyst. Notice the arrows meet in the middle — ML verdicts flow into RAG context, agent decisions flow "
         "into the knowledge base, and every automated action lands in the audit ledger. Detection, explanation "
         "and knowledge maintenance reinforce each other — that's the thesis contribution.")

# ======================================================================
# SLIDE 18b — LIVE DEMO (roadmap of what will be shown)
# ======================================================================
s = add_slide(MAGENTA)
title(s, "Live Demo —", "the system running", MAGENTA,
      "ordered most-important-first: real attack → detection → grounded explanation → the ML → the agent")
demo = [
    ("▶", "Real attack + attack-origin map", "Populate Map + Test the Shield — 14 families through the real Wazuh pipeline, scored live", RED),
    ("💬", "Grounded RAG explanation", "ask the analyst, click a source citation → open the exact indexed chunk in Qdrant", CYAN),
    ("🧠", "How the score was made", "the ML Engine page: 16 features → Isolation Forest + Autoencoder → fused tier", GREEN),
    ("🤖", "Autonomous CVE agent", "run it live — fetch → dedup → boost → LLM-score → index / queue / drop", AMBER),
]
y = Inches(1.85)
for glyph, head, body, col in demo:
    card = s.shapes.add_shape(9, Inches(0.7), y, Inches(11.9), Inches(1.05))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = col; card.line.width = Pt(1.5)
    tf = card.text_frame; tf.word_wrap = True
    tf.margin_left = Inches(0.28); tf.margin_top = Inches(0.16)
    p = tf.paragraphs[0]
    r = p.add_run(); r.text = glyph + "   "
    r.font.size = Pt(18); r.font.color.rgb = col
    r2 = p.add_run(); r2.text = head
    r2.font.size = Pt(17); r2.font.bold = True; r2.font.color.rgb = TEXT
    p2 = tf.add_paragraph()
    r3 = p2.add_run(); r3.text = "     " + body
    r3.font.size = Pt(13); r3.font.color.rgb = SOFT
    y += Inches(1.15)
notes(s, "Now I'll switch to the running system. I'll go in order of impact. First a real attack — I trigger 14 "
         "attack families as actual commands and you watch them get detected and mapped live. Then I ask the AI "
         "analyst to explain one, and click a citation to see the exact source it quoted. Then the ML Engine page "
         "shows HOW that anomaly score was produced — the two models and the fusion. Finally the CVE agent runs and "
         "maintains its own knowledge base. If anything lags, that's local CPU inference — it catches up.")

# ======================================================================
# SLIDE 19 — Results summary
# ======================================================================
s = add_slide(GREEN)
title(s, "Results at a", "glance", GREEN)
cards = [
    ("95.9%", "ATTACK RECALL", GREEN), ("89.2%", "ENSEMBLE F1", CYAN),
    ("8.0%", "FALSE-POSITIVE RATE", AMBER), ("75.1", "SCORE SEPARATION (PTS)", VIOLET),
    ("82.9%", "RAG HIT RATE@5", MAGENTA), ("98.3%", "CITATION PRECISION", GREEN),
    ("~12 ms", "SCORING LATENCY", CYAN), ("14/14", "ATTACK FAMILIES DETECTED", RED),
]
x0, y0 = Inches(0.7), Inches(1.7)
for i, (num, lab, col) in enumerate(cards):
    stat_card(s, x0 + (i % 4) * Inches(3.1), y0 + (i // 4) * Inches(1.85), Inches(2.9), num, lab, col)
bullets(s, Inches(0.75), Inches(5.6), Inches(12.0), Inches(1.5), [
    ("Every number is reproducible", "evaluation scripts, datasets and charts ship with the code", GREEN),
    ("Honest limitations", "PAM single-login detection 45% · faithfulness judged by same-family LLM · FP rate has headroom", AMBER),
], size=15)
notes(s, "Results: 95.9% recall, F1 89.2, 8% false positives, 75-point score separation, 82.9% RAG hit rate, 98.3% "
         "citation precision, 12-millisecond scoring, all 14 attack families detected. Every number is reproducible "
         "— the evaluation harness ships with the code. And the limitations are stated openly: single failed logins "
         "remain hard, generation faithfulness was judged by a same-family LLM, and the FP rate has headroom.")

# ======================================================================
# SLIDE 20 — Future work / closing
# ======================================================================
s = add_slide(MAGENTA)
title(s, "Future Work &", "Conclusion", MAGENTA)
bullets(s, Inches(0.65), Inches(1.55), Inches(12.2), Inches(3.4), [
    ("Temporal features", "rolling-window aggregates (failures/IP/10 min) to catch low-and-slow and single-event attacks", CYAN),
    ("Learned ensemble weights", "grid-search fusion weights on a validation split instead of fixed 0.45/0.55", GREEN),
    ("Stronger judge model", "independent LLM for generation eval; PR-curve driven threshold selection", VIOLET),
    ("Query expansion for weak categories", "LLM-rewritten queries to lift APT / C2 retrieval recall", AMBER),
    ("Cloud deployment", "Oracle ARM VM · Docker Compose · API gateway with auth + rate limiting (designed)", MAGENTA),
], size=15)
card = s.shapes.add_shape(9, Inches(0.65), Inches(5.15), Inches(12.1), Inches(1.5))
card.fill.solid(); card.fill.fore_color.rgb = PANEL
card.line.color.rgb = MAGENTA; card.line.width = Pt(2)
tf = card.text_frame; tf.word_wrap = True
tf.margin_left = Inches(0.35); tf.margin_top = Inches(0.22)
p = tf.paragraphs[0]
r = p.add_run(); r.text = "A SIEM that detects without labels, explains with citations, and updates its own knowledge — "
r.font.size = Pt(19); r.font.bold = True; r.font.color.rgb = TEXT
r2 = p.add_run(); r2.text = "auditable, local, and reproducible end-to-end."
r2.font.size = Pt(19); r2.font.bold = True; r2.font.color.rgb = MAGENTA
p2 = tf.add_paragraph()
r3 = p2.add_run(); r3.text = "Thank you — questions welcome."
r3.font.size = Pt(15); r3.font.color.rgb = SOFT
notes(s, "Future work: temporal window features for the last hard detection case; learned ensemble weights; an "
         "independent judge model for generation eval; query expansion for the weak retrieval categories; and the "
         "cloud deployment that's already designed. To conclude: this is a SIEM that detects without labels, "
         "explains with citations, and maintains its own knowledge — fully local, fully auditable, and "
         "reproducible end to end. Thank you.")

# ======================================================================
# The five slides below were added from the thesis PDF.
# They are appended as slides 21-25 so they are easy to find and reorder.
# Suggested final positions are noted in each header comment.
# ======================================================================

def simple_table(slide, x, y, w, headers, rows, col_widths, accent=CYAN, row_h=0.52, fs=12):
    """Lightweight table drawn with a python-pptx GraphicFrame."""
    from pptx.util import Inches as _In
    n_rows = len(rows) + 1
    tbl_shape = slide.shapes.add_table(n_rows, len(headers), x, y, w, _In(row_h * n_rows))
    tbl = tbl_shape.table
    for j, cw in enumerate(col_widths):
        tbl.columns[j].width = _In(cw)
    for j, h in enumerate(headers):
        c = tbl.cell(0, j)
        c.fill.solid(); c.fill.fore_color.rgb = PANEL
        p = c.text_frame.paragraphs[0]; r = p.add_run(); r.text = h
        r.font.size = Pt(fs); r.font.bold = True; r.font.color.rgb = accent
    for i, row in enumerate(rows, 1):
        for j, val in enumerate(row):
            c = tbl.cell(i, j)
            c.fill.solid(); c.fill.fore_color.rgb = BG
            p = c.text_frame.paragraphs[0]; r = p.add_run(); r.text = str(val)
            r.font.size = Pt(fs - 0.5)
            r.font.color.rgb = TEXT if j == 0 else SOFT
            if j == 0:
                r.font.bold = True
    return tbl_shape


# ---- SLIDE 21 (suggested position: after slide 5, Training Pipeline) ----
s = add_slide(GREEN)
title(s, "Training Data —", "two complementary sources", GREEN,
      "the model learns 'normal' locally and 'malicious' from the real world")
bullets(s, Inches(0.65), Inches(1.6), Inches(6.3), Inches(4.6), [
    ("Source 1 — Daily Wazuh collection", "collect_training_data.py runs via cron: reads alerts.json, filters by date, dedups by fingerprint (ts+rule+agent+msg), merges daily snapshots", CYAN),
    ("Teaches the baseline", "authentication, rootcheck, SCA, network monitoring — what THIS deployment's normal looks like", GREEN),
    ("Source 2 — WordPress plugin", "a live site under real attack for 2 weeks: brute force, SQLi probes, XSS payloads, automated scanning", MAGENTA),
    ("Teaches malicious patterns", "genuine attack behavior the local host would rarely produce on its own", RED),
], size=15)
stat_card(s, Inches(7.4), Inches(1.7), Inches(5.2), "2,171", "TOTAL ALERTS (D_train)", GREEN)
stat_card(s, Inches(7.4), Inches(3.35), Inches(2.5), "1,534", "BENIGN", CYAN)
stat_card(s, Inches(10.1), Inches(3.35), Inches(2.5), "637", "ATTACK", RED)
stat_card(s, Inches(7.4), Inches(5.0), Inches(5.2), "182", "HELD-OUT TEST SET (D_test)", AMBER)
notes(s, "Training data comes from two complementary sources. Source one: a daily collector, run by cron, that reads "
         "the live alerts file, filters by date, deduplicates with a fingerprint of timestamp, rule, agent and "
         "message, and merges daily snapshots — this teaches the model what THIS deployment's normal looks like. "
         "Source two: a WordPress security plugin on a live website under real attack for two weeks — brute force, "
         "SQL injection, XSS, scanning — giving genuine malicious patterns the local host rarely produces. Combined: "
         "2,171 alerts for training, 1,534 benign and 637 attack, plus a held-out test set of 182. The union is the "
         "point: local data defines normal, external data supplies real attacks.")

# ---- SLIDE 22 (suggested position: after slide 8, Autoencoder) ----
s = add_slide(VIOLET)
title(s, "Why These Two —", "algorithm comparison", VIOLET,
      "IF + AE were selected after evaluating the leading unsupervised alternatives for SIEM scoring")
simple_table(
    s, Inches(0.6), Inches(1.7), Inches(12.1),
    ["Method", "Weakness for SIEM", "Verdict"],
    [
        ["Isolation Forest", "random splits can miss subtle low-dim patterns", "SELECTED — best in ensemble"],
        ["Autoencoder (MLP)", "needs GPU / tuning; interpretability is poor", "SELECTED — best in ensemble"],
        ["One-Class SVM", "O(n²)–O(n³) training; impractical at SIEM scale", "Rejected — scalability"],
        ["Local Outlier Factor", "O(n²) kNN; no persistable model to score new points", "Rejected — no persistence"],
        ["Gaussian Mixture", "assumes Gaussian; poor on non-Gaussian security data", "Rejected — distribution assumption"],
        ["DBSCAN", "eps/min_samples sensitive; produces no anomaly score", "Rejected — no scoring output"],
    ],
    col_widths=[2.6, 6.2, 3.3], accent=VIOLET, row_h=0.62, fs=12.5)
txt(s, Inches(0.65), Inches(6.55), Inches(12), Inches(0.6),
    [("Linear-time scoring, model persistence, no distribution assumptions, and native anomaly scores — only IF + AE satisfy all four.", SOFT, False)], size=13)
notes(s, "Why these two specifically? I evaluated the leading unsupervised methods against the constraints of SIEM "
         "alert scoring: linear-time scoring, a persistable model that can score new points without retraining, no "
         "distribution assumptions, and a native anomaly score. One-Class SVM fails on scalability — cubic training. "
         "Local Outlier Factor has no persistable model. Gaussian Mixture assumes Gaussian data, which security data "
         "isn't. DBSCAN produces no score at all. Only Isolation Forest and the autoencoder satisfy every "
         "constraint, and — critically — they fail in opposite ways, which is what makes them a genuine ensemble "
         "rather than two copies of the same idea.")

# ---- SLIDE 23 (suggested position: after slide 6, Feature Engineering) ----
s = add_slide(CYAN)
title(s, "Feature Ablation —", "which signals actually matter", CYAN,
      "each variant fully retrained (<5 s on ~2,000 samples) and re-evaluated on the full unlabeled set")
pic(s, "ablation.png", Inches(1.5), Inches(1.55), w=Inches(10.3))
bullets(s, Inches(0.7), Inches(6.15), Inches(12.1), Inches(1.2), [
    ("Top 3 features", "privileged_account_change (−6.3% F1) · failed_count (−5.7%) · rule_level (−4.1%)", GREEN),
    ("mitre_count REJECTED", "+8.9% FP rate — train/prod distribution mismatch (Wazuh tags benign SSH logins with MITRE IDs)", RED),
], size=14)
notes(s, "To prove the feature set is earned, not guessed, I ran an ablation study — removing or adding one feature "
         "at a time and fully retraining, which takes under five seconds. Three features carry most of the "
         "discriminative power: privileged_account_change, worth 6.3 F1 points — remove it and new-user and "
         "promiscuous-mode attacks drop to zero detection; failed_count, the credential-attack signal; and "
         "rule_level, a severity prior. The instructive negative result: adding a semantically obvious feature — "
         "MITRE technique count — actually made things worse, plus 8.9% false positives, because Wazuh tags benign "
         "SSH logins with MITRE IDs, so the feature's distribution differs between training and production. "
         "Plausible is not the same as useful.")

# ---- SLIDE 24 (suggested position: after slide 11, ML Evaluation — REQUESTED) ----
s = add_slide(RED)
title(s, "Attack Testing &", "live map population", RED,
      "the pipeline is validated end-to-end against real, executed attacks — not synthetic feature vectors")
pic(s, "attack_sim.png", Inches(1.2), Inches(1.5), w=Inches(10.9))
bullets(s, Inches(0.7), Inches(6.15), Inches(12.1), Inches(1.2), [
    ("simulate_attack_for_wazuh.sh", "runs 14 attack families as real commands → Wazuh detects → ensemble scores (trojanized files, rootkit hidden files, PAM/SU failures, port changes, MITRE-tagged events T1548/T1078/T1110/T1014)", RED),
    ("populate_map.py", "injects synthetic alerts with real public source IPs → geolocated → Leaflet dark world map of attack origins", MAGENTA),
], size=13)
notes(s, "This is how the whole pipeline is validated. The attack-simulation framework — simulate_attack_for_wazuh.sh "
         "— executes 14 attack families as REAL commands on the host: trojanized-file signatures on /bin/passwd, "
         "kernel-rootkit hidden files in /tmp, PAM and SU authentication failures, listening-port changes, and "
         "MITRE-tagged events like T1548 sudo caching, T1078 valid accounts, T1110 password guessing, T1014 rootkit. "
         "Real Wazuh detects them, and the ensemble scores the authentic alerts — no synthetic feature vectors. "
         "Separately, populate_map.py injects alerts carrying real public source IPs, which the dashboard "
         "geolocates and plots on a dark Leaflet world map, so an analyst sees where attacks originate. Two "
         "validation paths, both converging on the dashboard.")

# ---- SLIDE 25 (suggested position: in RAG section, after slide 12) ----
s = add_slide(AMBER)
title(s, "Design Choices —", "RAG over fine-tuning", AMBER,
      "why retrieval, why MiniLM, why RRF instead of a cross-encoder")
simple_table(
    s, Inches(0.6), Inches(1.65), Inches(6.0),
    ["Dimension", "Fine-tune", "RAG"],
    [
        ["Knowledge update", "hours–days", "seconds"],
        ["Freshness", "frozen", "live"],
        ["Traceability", "opaque", "cited"],
        ["Privacy", "sent to model", "stays local"],
        ["Cost", "GPU training", "embed + search"],
    ],
    col_widths=[2.2, 1.9, 1.9], accent=AMBER, row_h=0.55, fs=12)
bullets(s, Inches(7.0), Inches(1.7), Inches(5.7), Inches(5.0), [
    ("Embedding: all-MiniLM-L6-v2", "384-dim, ~8 ms CPU — 5× faster than mpnet, keeps 90%+ quality; bigger models impractical on CPU", CYAN),
    ("Chunking: 512 tokens, 25% overlap", "won a [128/256/512/1024] sweep on Recall@5 — smaller fragments concepts, larger dilutes the vector", VIOLET),
    ("RRF, not cross-encoder", "ms-marco reranker HURT the domain (doesn't know rule 5710 ↔ SSH); RRF trusts rank position, no learned bias", GREEN),
    ("k = 5 retrieved", "maximizes Hit Rate within llama3.2's 8K window; k≥10 triggers 'lost in the middle'", MAGENTA),
], size=13)
notes(s, "Four design choices worth defending. First, RAG over fine-tuning: knowledge updates in seconds not days, "
         "answers are traceable and cited, and documents stay local — decisive for confidential security data. "
         "Second, the embedding model: all-MiniLM-L6-v2, 384 dimensions, about 8 milliseconds on CPU — five times "
         "faster than mpnet while keeping over 90% of the quality; the SOTA models are impractical on CPU. Third, "
         "chunk size 512 tokens with 25% overlap won a systematic sweep on Recall@5 — 128 fragments a concept, 1024 "
         "dilutes the embedding. Fourth, RRF instead of a cross-encoder: the ms-marco reranker actually hurt "
         "domain retrieval because it doesn't know rule 5710 relates to SSH; RRF makes no learned judgment, it just "
         "trusts rank position from two independent retrievers. And k=5 maximizes hit rate within llama's 8K "
         "context before the lost-in-the-middle effect sets in.")

# ======================================================================
# Slide transitions — smooth fade on every slide (professional, consistent).
# python-pptx has no transition API, so we inject the OOXML directly.
# ======================================================================
from pptx.oxml.ns import qn

def add_fade(slide, spd="med"):
    sld = slide._element
    for ex in sld.findall(qn("p:transition")):
        sld.remove(ex)
    trans = sld.makeelement(qn("p:transition"), {"spd": spd})
    trans.append(trans.makeelement(qn("p:fade"), {}))
    ref = sld.find(qn("p:clrMapOvr"))
    if ref is None:
        ref = sld.find(qn("p:cSld"))
    ref.addnext(trans)

for _sl in prs.slides:
    add_fade(_sl, spd="med")

out = os.path.join(HERE, "AI_Threat_Engine_Presentation.pptx")
prs.save(out)
print(f"Saved {out}  ({len(prs.slides.__iter__.__self__._sldIdLst)} slides)")
